### ISSUE TITLE
Binary resources and content location 

### ISSUE THREAD

**Issue by atomotic** [ghukill/pyfc4#59]
there is something strange in using **binary.location**, but i'm not able to troubleshoot it

given this example:

	from pyfc4.models import *
	import requests
	
	fedora_root = "http://localhost:8080/rest"
	repo = Repository(fedora_root, None, None)
	
	urls = [
	    "http://ia601206.us.archive.org/32/items/Mondo.2000.Issue.01.1989/Mondo.2000.Issue.01.1989_djvu.txt",
	    "http://ia601206.us.archive.org/32/items/Mondo.2000.Issue.01.1989/Mondo.2000.Issue.01.1989_djvu.xml"
	]
	
	items = BasicContainer(repo, "items")
	items.create(specify_uri=True)
	
	for url in urls:
	    path = "items/{path}".format(path=url.rsplit('/', 1)[-1])
	    print(path)
	    content_type = requests.head(url).headers.get('content-type')
	
	    fc_file = Binary(repo, path)
	    fc_file.binary.location = url
	    fc_file.binary.mimetype = content_type
	    fc_file.create(specify_uri=True)

i've sniffed the http traffic to fedora, what i see:

	sudo ngrep -d lo0 -W byline -qilw 'put' tcp dst port 8080
	...
		
	PUT /rest/items HTTP/1.1.
	
	
	PUT /rest/items/Mondo.2000.Issue.01.1989_djvu.txt HTTP/1.1.
	Content-Type: text/plain.
	Content-Location: http://ia601206.us.archive.org/32/items/Mondo.2000.Issue.01.1989/Mondo.2000.Issue.01.1989_djvu.txt.
	
	
	PUT /rest/items/Mondo.2000.Issue.01.1989_djvu.xml HTTP/1.1.
	Content-Type: text/plain.
	Content-Location: http://ia601206.us.archive.org/32/items/Mondo.2000.Issue.01.1989/Mondo.2000.Issue.01.1989_djvu.txt.
	
every new resource created keeps the same **Content-Location**  
where i am wrong?

**Comment by ghukill** [comment]
Thanks for catching this, I'm able to recreate what you're seeing.  Have to step away for a bit, but will investigate and follow-up ASAP.

**Comment by ghukill** [comment]
Well, I see why this is happening, but untangling the class instantiating and inheritance that is causing it.

It also touches on an area I wasn't terribly happy with, that of prioritizing values set in `self.headers` over object attributes.  For example, if `fc_file.headers['Content-Location']` is set, it will ignore anything set at `fc_file.binary.location`.  The idea was that headers will override all, as they might be conveniently set all at once.  But, it's a little non-intuitive why a resource has header information in the first place, when that really only applies to actual request/responses.

It probably makes more sense to have object attributes capture the information that will be needed for setting headers for requests (e.g. mimetype, binary location, etc.), and then set the headers explicitly each time.  

Maybe save the headers from the last request in something like `self._last_call.headers`, as they can be helpful to have around.  But that's another question.

Re: this particular bug, looking into fixing the class initialization and inheritance right now.  Thanks again for starting this issue!  Everything is still a bit rough around the edges, most helpful.

**Comment by ghukill** [comment]
Okay, got a fix in place.

Instead of passing `data`, `headers`, and `status_code` for various resource types, now passing the full `response` from a `GET` request to retrieve a resource.  This was, at least right now, the only time when a resource is instantiated with data or headers.  More importantly, the response object is immutable, meaning that it won't get mutated between instances of resources.

In short, addresses the problem above.  Still allows for setting headers like `foo.headers['Content-Type']` or `foo.headers['Content-Location']` for binary resource creation, if that should prove helpful.

Finally, still considering the utility of saving requests and responses to a resource instance in something like `self._requests` and `self._responses`.  These could be used for pulling data/headers from past responses, double checking requests just made, etc.  Currently saving a resource's graph before modification at `self.rdf._orig_graph`, so doing a version of this already.  

@atomotic, hopefully this addresses what you first reported, and hope this works moving forward.  Will leave this issue open for now, maybe some more tests, and close when confident it's working.

**Comment by atomotic** [comment]
great, thanks for fixing it!
setting `headers` seems working fine, i'm testing with this simple script (very quick and dirty at the moment): https://github.com/atomotic/iafc

**Comment by ghukill** [comment]
Seems to be working okay, closing the issue, thanks again for reporting.
